{"name": "Проверка ошибки авторизации несуществующего курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'zCnQCV', 'password': 'nnxGyO'}"}, {"name": "status_code", "value": "404"}, {"name": "response_text", "value": "{'code': 404, 'message': 'Учетная запись не найдена'}"}], "start": 1736673026459, "stop": 1736673026715, "uuid": "613518e4-f1cb-44c1-8545-bb7a07bc2b6c", "historyId": "efd38415b45389830c57b39974e9d445", "testCaseId": "7391b43a477e729412655a4faee92fb0", "fullName": "tests.test_login_courier.TestLoginCourier#test_not_exists_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "30780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}