{"name": "Проверка ошибки авторизации несуществующего курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'lguYcS', 'password': 'PrXJtm'}"}, {"name": "status_code", "value": "404"}, {"name": "response_text", "value": "{'code': 404, 'message': 'Учетная запись не найдена'}"}], "start": 1736673793799, "stop": 1736673794107, "uuid": "c1f08188-475e-462c-8320-d74e3c28306a", "historyId": "52d11bf8ced67bd63bb2c5d9ab8c5676", "testCaseId": "7391b43a477e729412655a4faee92fb0", "fullName": "tests.test_login_courier.TestLoginCourier#test_not_exists_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "42088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}